options:
  debug:
    default: False
    description: Enable debug logging.
    type: boolean
  os-admin-hostname:
    default: glance.juju
    description: |
      The hostname or address of the admin endpoints that should be advertised
      in the glance image provider.
    type: string
  os-internal-hostname:
    default: glance.juju
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the glance image provider.
    type: string
  os-public-hostname:
    default: glance.juju
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the glance image provider.
    type: string
  region:
    default: RegionOne
    description: Space delimited list of OpenStack regions
    type: string
  api_service:
    default: heat-api
    description: |
      Value should be one of heat-api or heat-api-cfn. The configuration parameter
      is only applicable during the initial deploy of the charm and change in the
      configuration does not have any effect once deployed.
    type: string
